# Setup
title:            Tejas Kasetty
email:            'kasetty.tejas@gmail.com'
description:      [Artificial Intelligence,] #Congnitive Neuroscience]
url:              https://tejaskasetty.github.io
baseurl:
info: Learn more about Tejas Kasetty, his research, and interests.

author:
  name:           'Tejas Kasetty'
  url:            https://tejaskasetty.github.io

#profile: /assets/img/brain-logo-icon.avif
profile: /assets/img/profile_picture.webp
favicon: /assets/img/favicon.ico
cv: /assets/pdf/Tejas_Kasetty_CV.pdf
# kramdown:
#   input: GFM

include:
  - _pages
  - _data
  - assets

collections:
  pages:
    output: true


# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
# paginate:         5

